export const SEARCH_CITY_DATA_REQUEST = "SEARCH_CITY_DATA_REQUEST";
export const SEARCH_CITY_DATA_SUCCESS = "SEARCH_CITY_DATA_SUCCESS";
export const SEARCH_CITY_DATA_FAILURE = "SEARCH_CITY_DATA_FAILURE";
